version: '3'
services:
  frontend:
    build:
      context: ./frontend
    env_file:
      - /.frontend/.env.sample
    ports:
      - "5173:5173"
  

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.sample
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data:/data
