name: Docker Image CI

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest


    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Docker
        run: |
               docker --version
               docker compose version

      - name: Stop Old Containers
        run: |
               docker compose down || true

      - name: Build Images
        run: |
               docker compose build

      - name: Start Containers
        run: |
               docker compose up -d



      - name: Verify
        run: |
          docker ps
